wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.10
    start_time: 1661823396.449287
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.10
      5: 0.13.2
      8:
      - 2
      - 5
